
name: AWS Integration Demo

on: 
  push: 
    branches: ["main"] 

jobs:
  aws-demo:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::963777256626:role/github-rule
          aws-region: us-east-1

      - name: Who am I in AWS?
        run: aws sts get-caller-identity
      - name: List s3 buckets
        run: aws s3 ls
